export const appSettings = {
  appVersion: process.env.REACT_APP_VERSION,
  apiURL: 'https://api.wallet.conceal.network/api',
  homePage: 'https://conceal.network',
  explorerURL: 'https://explorer.conceal.network',
  poolURL: 'https://pool.conceal.network',
  coingeckoAPI: 'https://api.coingecko.com/api/v3',
  discord: 'https://discord.gg/QY4ksas',
  twitter: 'https://twitter.com/ConcealNetwork',
  reddit: 'https://www.reddit.com/r/ConcealNetwork',
  telegram: 'https://t.me/concealnetworkusers',
  medium: 'https://medium.com/@ConcealNetwork',
  coinGecko: 'https://coingecko.com/en/coins/conceal',
  coinMarketCap: 'https://coinmarketcap.com/currencies/conceal',
  updateBlockchainHeightInterval: 30,  // seconds
  updateMarketPricesInterval: 120,  // seconds
  maxWallets: 2,
  coinDecimals: 5,
  defaultFee: 0.0001,
  messageFee: 0.001,
  selfDestructMessageFee: 0.0001,
  feePerChar: 0.00001,
  depositFee: 0.001,
  investmentFee: 0.001,
  withdrawalFee: 0.0001,
  qrCodePrefix: 'conceal',
  donationURL: 'https://conceal.cloud/donate',
  IPNURL: 'https://conceal.cloud/pay',
};
